server:
  port: 5003
spring:
  application:
    name: provider-server
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:5001/eureka/