server:
  port: 5003
spring:
  application:
    name: provider-server
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:5001/eureka/,http://127.0.0.1:6001/eureka/